// Auto-generated file - DO NOT EDIT
// Generated by system_sequence_generator.zig

/// Pre-computed system execution order sorted by phase and dependencies
pub const execution_order: []const usize = &.{ 5, 0, 11, 2, 4, 6, 7, 8, 3, 10, 1, 9 };

/// System indices grouped by phase (for debugging)
pub const phase_boundaries = struct {
    pub const Input = .{ .start = 0, .end = 2 };
    pub const PreUpdate = .{ .start = 2, .end = 3 };
    pub const Update = .{ .start = 3, .end = 8 };
    pub const PostUpdate = .{ .start = 8, .end = 11 };
    pub const Render = .{ .start = 11, .end = 12 };
};
