// Generated by: zig build registry
// System dependency metadata extracted via static analysis

pub const SystemMetadata = struct {
    name: []const u8,
    reads: []const []const u8,
    writes: []const []const u8,
    runs_before: []const []const u8,
    runs_after: []const []const u8,
    has_queries: bool,
};

pub const all_metadata: []const SystemMetadata = &.{
    .{
        .name = "AIManager",
        .reads = &.{"Position", "Speed"},
        .writes = &.{"AI", "Velocity"},
        .runs_before = &.{"Movement"},
        .runs_after = &.{"WaveManager"},
        .has_queries = true,
    },
    .{
        .name = "Animate",
        .reads = &.{},
        .writes = &.{"Sprite"},
        .runs_before = &.{},
        .runs_after = &.{},
        .has_queries = true,
    },
    .{
        .name = "Attack",
        .reads = &.{"Slime", "Energy"},
        .writes = &.{"Attack"},
        .runs_before = &.{},
        .runs_after = &.{},
        .has_queries = true,
    },
    .{
        .name = "ChangeAnim",
        .reads = &.{},
        .writes = &.{"Sprite", "Texture", "BoundingBox", "Slime"},
        .runs_before = &.{"Animate"},
        .runs_after = &.{},
        .has_queries = true,
    },
    .{
        .name = "Collision",
        .reads = &.{"Position", "Sprite", "Slime", "Wave"},
        .writes = &.{"BoundingBox"},
        .runs_before = &.{"ChangeAnim", "Animate"},
        .runs_after = &.{},
        .has_queries = true,
    },
    .{
        .name = "Controller",
        .reads = &.{"Controller", "Speed"},
        .writes = &.{"Slime", "Sprite", "Velocity", "Attack"},
        .runs_before = &.{"AIManager", "Animate", "Attack", "ChangeAnim", "EnergyManager", "WaveManager"},
        .runs_after = &.{},
        .has_queries = true,
    },
    .{
        .name = "EnergyManager",
        .reads = &.{},
        .writes = &.{"Energy", "Slime"},
        .runs_before = &.{"ChangeAnim"},
        .runs_after = &.{},
        .has_queries = true,
    },
    .{
        .name = "HealthManager",
        .reads = &.{"Controller"},
        .writes = &.{"Health"},
        .runs_before = &.{"OtherSystem"},
        .runs_after = &.{},
        .has_queries = true,
    },
    .{
        .name = "Movement",
        .reads = &.{"Velocity"},
        .writes = &.{"Position"},
        .runs_before = &.{},
        .runs_after = &.{},
        .has_queries = true,
    },
    .{
        .name = "Render",
        .reads = &.{"Position", "Text", "Color", "Texture", "Sprite", "Rectangle", "Circle", "StatusBar", "BoundingBox"},
        .writes = &.{},
        .runs_before = &.{},
        .runs_after = &.{},
        .has_queries = true,
    },
    .{
        .name = "UpdateStatusBar",
        .reads = &.{},
        .writes = &.{"StatusBar"},
        .runs_before = &.{},
        .runs_after = &.{},
        .has_queries = true,
    },
    .{
        .name = "WaveManager",
        .reads = &.{"SlimeRef"},
        .writes = &.{"Position", "Sprite", "Wave"},
        .runs_before = &.{"Movement", "Animate", "ChangeAnim", "Render"},
        .runs_after = &.{},
        .has_queries = true,
    },
};

/// Pre-computed execution order based on dependencies
pub const execution_order: []const usize = &.{5, 7, 10, 6, 11, 0, 8, 4, 3, 1, 2, 9};
