//! Prescient ECS Library
const std = @import("std");

// Public API exports
pub const Prescient = @import("ecs/Prescient.zig").Prescient;

// Core ECS - these are library mechanisms
pub const EntityManager = @import("ecs/EntityManager.zig");
pub const PoolManager = @import("ecs/PoolManager.zig");
pub const SystemManager = @import("ecs/SystemManager.zig");

// Pool mechanisms
pub const EntityPool = @import("ecs/EntityPool.zig");
pub const PoolInterface = @import("ecs/PoolInterface.zig");
pub const ArchetypePool = @import("ecs/ArchetypePool.zig");
pub const SparseSetPool = @import("ecs/SparseSetPool.zig");

// Query system
pub const Query = @import("ecs/Query.zig");
pub const QueryTypes = @import("ecs/QueryTypes.zig");

// Utilities
pub const EntityBuilder = @import("ecs/EntityBuilder.zig");
pub const MaskManager = @import("ecs/MaskManager.zig");
pub const StorageStrategy = @import("ecs/StorageStrategy.zig");

// NOTE: ComponentRegistry, PoolRegistry, SystemRegistry are NOT exported
// They are project-specific and generated by build tools
